spring:
  h2:
    console:
      enabled: true
  datasource:
    druid:
      url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1
      username: sa
      password: null
      initial-size: 5
      min-idle: 0
      max-active: 20
    schema: ./xo-starter-demo-db/init.sql
    data: ./xo-starter-demo-db/data.sql
  jpa:
    database: h2
    show-sql: true
    properties:
      hibernate:
        search:
          default:
            elasticsearch:
              host: http://localhost:9200
xo:
  api:
    doc:
      title: 用户端服务
      description: 用户端服务接口
      version: 1.0
      base-package: com.github.jnoee.xo.starter.demo.visit.controller
logging:
  level:
    com:
      github:
        jnoee: DEBUG