spring:
  h2:
    console:
      enabled: true
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.250/xo?autoReconnect=true&amp;characterEncoding=UTF-8
      username: cm
      password: cm
      initial-size: 5
      min-idle: 0
      max-active: 20
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        search:
          default:
            elasticsearch:
              host: http://localhost:9200
xo:
  api:
    doc:
      title: 工作人员后台管理服务
      description: 工作人员后台管理服务接口
      version: 1.0
      base-package: com.github.jnoee.xo.starter.demo.work.controller
logging:
  level:
    com:
      github:
        jnoee: DEBUG